### ISSUE TITLE
Rename `astra/torch/al/acquisitions/random.py` file

### ISSUE THREAD

**Issue by jaiswalsuraj487** [sustainability-lab/ASTRA#4] opened 2023-10-27 23:28 UTC
Please rename the file `astra/torch/al/acquisitions/random.py` to `astra/torch/al/acquisitions/random_acquistion.py` as the previous one conflicts with file `numpy/random` and creates a circular dependency.

**Comment by patel-zeel** [comment] 2023-10-28 00:32
@jaiswalsuraj487 Can you please give more details along with failure logs?

**Comment by nipunbatra** [comment] 2023-10-28 01:37
@jaiswalsuraj487 

Can you give a [MWE](https://stackoverflow.com/help/minimal-reproducible-example) to illustrate the bug? 

@patel-zeel you can link the MWE from StackOverflow in the Issue Template.

**Comment by patel-zeel** [comment] 2023-10-28 02:17
@nipunbatra Sir, I have added a template inspired from [optree](https://github.com/metaopt/optree/issues/new/choose) and added reading the [MWE](https://stackoverflow.com/help/minimal-reproducible-example) as a prerequisite.

**Comment by jaiswalsuraj487** [comment] 2023-10-28 02:18
By running the file `astra/torch/al/acquisitions/base.py`, we get the below error:
```python
(torch_gpu) jaiswalsuraj@ramanujan:~/suraj_work$ python3 ASTRA/astra/torch/al/acquisitions/base.py
Traceback (most recent call last):
  File "/home/jaiswalsuraj/suraj_work/ASTRA/astra/torch/al/acquisitions/base.py", line 2, in <module>
    import numpy as np
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/site-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/site-packages/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/site-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 38, in init numpy.random.bit_generator
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/secrets.py", line 19, in <module>
    from random import SystemRandom
  File "/home/jaiswalsuraj/suraj_work/ASTRA/astra/torch/al/acquisitions/random.py", line 1, in <module>
    import torch
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/site-packages/torch/__init__.py", line 27, in <module>
    from ._utils_internal import get_file_path, prepare_multiprocessing_environment, \
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/site-packages/torch/_utils_internal.py", line 3, in <module>
    import tempfile
  File "/home/jaiswalsuraj/miniconda3/envs/torch_gpu/lib/python3.10/tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random' from partially initialized module 'random' (most likely due to a circular import) (/home/jaiswalsuraj/suraj_work/ASTRA/astra/torch/al/acquisitions/random.py)
```

**Comment by patel-zeel** [comment] 2023-10-28 02:29
@jaiswalsuraj487 I can reproduce this error locally, but it does not seem to affect the [test case](https://github.com/sustainability-lab/ASTRA/blob/main/tests/torch/acquisitions/test_random.py) I am running. Can you mention if you were trying to import something and then it failed with the above error?

**Comment by jaiswalsuraj487** [comment] 2023-10-28 03:38
No. I faced the above error only locally in folder `astra/torch/al/acquisitions/`

**Comment by patel-zeel** [comment] 2023-10-28 04:31
@jaiswalsuraj487 So, are there any action items for me in this issue? Are you facing any hurdles in tasks assigned to you due to this issue?

**Closed** 2023-10-28 06:54 UTC
